author: SwearWord
main: org.blockface.careers.Careers
name: Careers
url: http://blockface.org/
version: ${project.version}-b${build.number}
softdepend: [ChunkyVillage]
commands:
    setjob:
        description: Set job.
        usage: /setjob <career> [player]
        permission: careers.setjob
    jobinfo:
        description: See info about job.
        usage: /info
    addexp:
        description: Add experience points.
        usage: /addexp <number>
        permission: careers.addexp
    setjail:
        description: Set jail.
        usage: /setjail
        permission: careers.setjail
    joblist:
        description: See jobs.
        usage: /joblist
permissions:
    careers.nohell:
        description: No Hell
        default: op